### PR TITLE
fix: typing notifier compatibility with mobile improvements module

### PR DESCRIPTION
**Pull request by Asinphi**
Typing notifier previously wouldn't work with Mobile Improvements present because CGMP monkey patches ChatLog._onChatKeyDown but typing in the original chatbox doesn't call ChatLog._onChatKeyDown.
Solution: when Mobile Improvements is present, still listen to the chat box keydown event in addition to monkey patching _onChatKeyDown to see when the Mobile Improvements send button is pressed.

I identified this bug on Foundry v10 build 291 (latest stable release at the time of this pull request) with the dnd 5e system.

### CODE REVIEW

**Comment by cs96and** [comment]
I'm not sure I want to merge this, as Mobile Improvements has not been updated for v10.

**Comment by Asinphi** [comment]
From my testing, Mobile Improvements still works fine on v10, and since there doesn't seem to be any alternative modules, there might be some who use it.

**Comment by cs96and** [comment]
I just tried this in v10.303, and it does not seem to fix the issue.  No typing notifications are generated.

**Comment by cs96and** [comment]
This is now fixed in v1.4.0.

Thanks for the PR, and sorry for the delay!

**Pull request merged**
